package com.zamaflow.bpm.api.domain.enumeration;

/**
 * The InfringementActionType enumeration.
 */
public enum InfringementActionType {
    CREATED_INFRINGEMENT, INFRINGEMENT_NOTIFICATION_SENT, INFRINGEMENT_REMINDER_NOTIFICATION_SENT, INFRINGEMENT_ADMIN_REMINDER_NOTIFICATION_SENT, INFRINGEMENT_PAYMENT_DONE, INFRINGEMENT_DRIVER_NOMINATION, INFRINGEMENT_ASSIGN_ANOTHER_DRIVER, INFRINGEMENT_CANCEL, INFRINGEMENT_CREATED_COURT_CASE, INFRINGEMENT_ASSIGN_DRIVER, INFRINGEMENT_CREATE_DEMERIT, INFRINGEMENT_CANCEL_DEMERIT, INFRINGEMENT_CREATE_FINE, INFRINGEMENT_PAY_FINE
}
